syntax = "proto3";

import "./chattingRequest.proto";
import "./chattingResponse.proto";

package packet;

message ChattingCommonPacket{
    uint32 packetType = 1;
    uint32 versionLength = 2;
    string version = 3;
    uint32 sequence = 4;    
    uint32 payloadLength = 5;
    bytes payload = 6;
}

message ChattingPacket{
    oneof chattingPayload{
        C2SChattingServerLoginRequest chattingServerLoginRequest = 1001;
        S2CChattingServerLoginResponse chattingServerLoginResponse = 1002;  
        C2SChattingServerCreateRoomRequest chattingServerCreateRoomRequest = 1003;
        S2CChattingServerCreateRoomResponse chattingServerCreateRoomResponse = 1004; 
        C2SChattingServerJoinRoomRequest chattingServerJoinRoomRequest = 1005; 
        C2SChattingServerLeaveRoomRequest chattingServerLeaveRoomRequest = 1006;
        C2SChattingServerChatSendRequest chattingServerChatSendRequest = 1007;
        S2CChattingServerChatSendResponse chattingServerChatSendResponse = 1008; 
    }
}